config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {
    # Override the following Devise controllers with our custom versions
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :users
  end

  # form_for is easier to use with a resourceful route
  resources :contact_forms, only: [:create]
  # A non-resourceful route was used to place the contact form at /contact
  get 'contact' => 'contact_forms#new', as: 'contact'
end

app/views/layouts/_base_menu_items.html.erb
<%# Menu items that that should appear in the navbar of all logged-in users,
regardless of their roles %>

app/views/layouts/admin.html.erb
<% content_for :navigation_menu do %>
  <%# Menu items that that should only appear in the navbar of users with
  "admin" role %>
  <li><%= link_to t('navigation.users'), admin_users_path %></li>

  <%= render 'layouts/base_menu_items' %>
<% end %>

<%# Render the base layout (application.html.erb), to which this layout will
pass the menu items %>
<%= render template: "layouts/application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Project Name" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Insert description" %>">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<%# Giving the body tag classes with names corresponding to the current
controller and action allows the implementation of page-specific CSS and JS %>
<body class="<%= "#{controller_name}-controller #{action_name}-action #{layout_name}-layout" %>">
  <header>
    <%# navigation styled for Bootstrap 3.0 %>
    <nav class="navbar-default navbar-fixed-top navbar-custom">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
            <%= link_to image_tag('logo.png'), root_path, class: 'navbar-brand', alt: 'Project Name' %>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%# The "Home" and "Contact" menu items are here (and not in a
            partial) because of their order. We want "Home" to be the first
            item of the navbar and "Contact" to be the last %>
            <li><%= link_to t('navigation.home'), root_path %></li>
            <%= yield(:navigation_menu) %>
            <li><%= link_to t('navigation.contact'), contact_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <%# Devise %>
            <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><b><%= current_user.full_name %></b> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('navigation.edit-profile'),
                                    edit_user_registration_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#"><%= link_to t('navigation.sign-out'),
                                                destroy_user_session_path,
                                                method: 'delete' %></a></li>
                  </ul>
                </li>
            <% else %>
                <li><%= link_to t('navigation.sign-up'), new_user_registration_path %></li>
                <li><%= link_to t('navigation.sign-in'), new_user_session_path %></li>
            <% end %>
          </ul>

        </div><!-- navbar-collapse -->
      </div><!-- container-fluid -->
    </nav>
  </header>


  <main role="main">
    <div class="container-fluid">
      <div id="flash-messages" class="row">
        <%# Rails flash messages styled for Bootstrap 3.0 %>
        <% flash.each do |type, message| %>
          <%# Checking if the message is a string is required to avoid the
          Devise timeoutable module from creating a flash message containing
          "true". This is a temporary fix as it was just fixed in Devise (but
          not on the master branch yet) See:
          https://github.com/plataformatec/devise/issues/1777 %>
          <% if message.is_a?(String) %>
            <%= content_tag :div, class: "alert #{bootstrap_class_for(type)} alert-dismissable", role: "alert" do %>
              <button type="button" class="close" data-dismiss="alert"><i class="glyphicon glyphicon-remove-circle"></i></button>
              <%= message %>
            <% end %>
          <% end %>
        <% end %>
      </div><!-- flash-messages -->

      <%# Main content %>
      <%= content_for?(:main_contents) ? yield(:main_contents) : yield %>
    </div><!-- container-fluid -->
  </main>

  <%# footer styled for Bootstrap 3 %>
  <footer>
    <div class="container-fluid footer text-center">
      <div class="row">
        <footer class="footer">
          <div class="container">
            <p class="text-muted">&copy; Project Name</p>
          </div>
        </footer>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/layouts/guest.html.erb
<% content_for :navigation_menu do %>
  <%# Menu items that that should only appear in the navbar of
  unauthenticated (guest) users %>

<% end %>

<%# Render the base layout (application.html.erb), to which this layout will
pass the menu items %>
<%= render template: "layouts/application" %>

app/views/layouts/user.html.erb
<% content_for :navigation_menu do %>
  <%# Menu items that that should only appear in the navbar of users with
  "user" role (non-admin users) %>

  <%= render 'layouts/base_menu_items' %>
<% end %>

<%# Render the base layout (application.html.erb), to which this layout will
pass the menu items %>
<%= render template: "layouts/application" %>